export enum BookingStatus {
  BOOKING_CREATED = 'BOOKING_CREATED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  WAITING_FOR_SERVICE = 'WAITING_FOR_SERVICE',
  STAFF_ASSIGNED = 'STAFF_ASSIGNED',
  STAFF_ON_THE_WAY = 'STAFF_ON_THE_WAY',
  ARRIVED = 'ARRIVED',
  VEHICLE_RECEIVED = 'VEHICLE_RECEIVED',
  VEHICLE_INSPECTION = 'VEHICLE_INSPECTION',
  WASHING = 'WASHING',
  DETAILING = 'DETAILING',
  FINAL_INSPECTION = 'FINAL_INSPECTION',
  WAITING_FOR_CUSTOMER_CONFIRMATION = 'WAITING_FOR_CUSTOMER_CONFIRMATION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ISSUE_REPORTED = 'ISSUE_REPORTED',
  PAYMENT_REMAINING = 'PAYMENT_REMAINING'
}
